version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    docker:
      - image: circleci/node:10.20.1
      - image: circleci/mongo:4.13.20
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
      - run: npm test

workflows:
  build-and-test:
    jobs:
      - build-and-test