version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node
      - image: circleci/mongo:4.2.1
    executor:
      name: node/default
      tag: '10.20.1'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
    steps:
      - checkout
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build
      - test:
        requires:
          - build